### ISSUE TITLE
API documentation missing OPTION verb for `/todos`

### ISSUE THREAD

**Issue by p2635** [eviltester/thingifier#21]
Hi @eviltester, thank you for creating this free resource for learning API testing. I will start logging improvements or anything that I think is odd as I go through the course. If I get extra time, I could also submit a PR (if it's something that I can contribute to) but I'm going to just log as an issue for now.

For challenge ID 24, it relates to sending an OPTIONS request for todos. When I was reading the docs on https://apichallenges.herokuapp.com/docs, I noticed it was not there. I think a minor edit would suffice to add a line there.

**Comment by eviltester** [comment]
Thanks, done.
