### ISSUE TITLE
/todos `OPTIONS` API response - 204 No Content received instead of 200 OK

### ISSUE THREAD

**Issue by p2635** [eviltester/thingifier#22]
This relates to Challenge 24. Am I doing something wrong? Perhaps this is the expected result and the challenge just needs updating.

<img width="1020" alt="image" src="https://github.com/eviltester/thingifier/assets/4522927/50f4a5a0-9993-4a46-8522-d7a37058b235">

**Comment by eviltester** [comment]
Thanks.

You are quite correct. The original challenge code returned a 200, and I changed the underlying generic API builder to return 204.

204 is the 'more correct' status code becuase there is no content in the response. But, APIs work differently and part of the joy of testing APIs is finding inconsistencies.

I've amended the code to return a 200 for this set of options to allow the challenge to pass.

**Comment by eviltester** [comment]
checkedin code
