### ISSUE TITLE
API response from `GET /challenger/:guid` - 'TITILE' typo

### ISSUE THREAD

**Issue by p2635** [eviltester/thingifier#25]
See screenshot below, it says 'TITILE' instead of 'TITLE'
<img width="1021" alt="image" src="https://github.com/eviltester/thingifier/assets/4522927/ffa1a014-15f1-4b83-bf7d-86d5775dab44">

**Comment by eviltester** [comment]
Thanks for reporting, since this is an internal code it requires a bit more effort to fix, otherwise the saved state would be invalid.

I'll consider this for the future.

**Comment by eviltester** [comment]
Thanks, I decided to fix it.
