### ISSUE TITLE
API challenges documentation - improvement to 'Open API file'

### ISSUE THREAD

**Issue by p2635** [eviltester/thingifier#26]
Link: https://apichallenges.herokuapp.com/

Under the headings 'Simple API', 'API Challenges', 'API Simulator', 'HTTP mirror', there is an option called 'Open API file'. I mistakenly thought this was a feature to open an API file or something. After more investigation, it turns out this is the OpenAPI swagger file. So I would recommend to rename this to 'Download OpenAPI Swagger File' to avoid confusion for anyone else.

<img width="1027" alt="image" src="https://github.com/eviltester/thingifier/assets/4522927/282f7eb7-a6d8-4577-8175-8b328ac2626c">

**Comment by eviltester** [comment]
Thanks, I'll update the UI
